language: node_js
node_js: node
branches:
  except: /^v\d/
before_install: curl -sSL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/bin '*/stack'
cache:
  directories: ~/.stack
