platform: x64
shallow_clone: true
skip_tags: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: 83HiACEYngc2//OzcISIcJuUpp/pidzqkYDXAL95gOWA0Djz1rEoyaH8K48eXL6G
install:
  - curl --silent --show-error --output stack.zip --location --insecure https://www.stackage.org/stack/windows-x86_64
  - 7z x stack.zip stack.exe
  - ps: Install-Product node Stable x64
  - npm install
build: off
before_test: stack setup > nul
test_script: npx nyc node test.js
on_success:
  - npx nyc report --reporter=text-lcov | npx coveralls
